# Generated by Django 6.1 on 2026-09-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
